SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [Disallow_Securitychanges] ON DATABASE 
	FOR ADD_ROLE_MEMBER, DROP_ROLE_MEMBER, DROP_USER, CREATE_USER, DROP_ROLE, ALTER_USER
AS 
IF IS_SRVROLEMEMBER('sysadmin') = 0
BEGIN
   PRINT 'Only sysadmins can perform this task, please get with the DBA team!' 
   ROLLBACK TRANSACTION
END
GO
DISABLE TRIGGER Disallow_Securitychanges ON DATABASE
GO
