IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'COEXIST\RG-MIS-DB Dev General')
CREATE LOGIN [COEXIST\RG-MIS-DB Dev General] FROM WINDOWS
GO
CREATE USER [COEXIST\RG-MIS-DB Dev General] FOR LOGIN [COEXIST\RG-MIS-DB Dev General]
GO
